# Generated by Django 4.1.3 on 2022-11-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('plain_doc', models.FileField(upload_to='plain_training')),
                ('json_doc', models.ImageField(null=True, upload_to='trained')),
            ],
        ),
    ]
